### ISSUE TITLE
12.3 two hr managers = broken

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#473] opened 2017-08-11 22:38 UTC
![image](https://user-images.githubusercontent.com/10689073/29234317-6b3c55fe-7ef6-11e7-9b03-9bc009767dac.png)
vs
![image](https://user-images.githubusercontent.com/10689073/29234323-755f4ee2-7ef6-11e7-999f-971635111aac.png)
[sg_8bac7aa2-d.zip](https://github.com/hovgaardgames/startupcompany/files/1219239/sg_8bac7aa2-d.zip)

**Comment by johannwagner** [comment] 2017-08-12 00:22
Could you explain the issue ?

**Comment by legaultp1** [comment] 2017-08-12 05:02
the issue is that the 2 HR can control the same managers
if this is by design, it is ok otherwize, if it is not by design. this is an issue
like a a staff member can only have 1 manager.
should the manager themselves only have 1 HR? or can they have multiple HR managers?

**Comment by jhovgaard** [comment] 2017-12-18 12:51
Nice catch. Fixed in Beta 14!

**Closed by jhovgaard** 2017-12-18 12:51 UTC
Labels: p:minor, s:approved, t:bug
