### ISSUE TITLE
Beta 9.4: Money Display Disappeared

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#262] opened 2017-03-22 05:55 UTC
Sometime after reaching T5 and hiring a CTO, the money display disappears and no longer shows the current bank balance, but shows blank.

**Comment by metathias** [comment] 2017-03-22 06:27
Experienced the same Issue around that tier. Have not hired CTO though.

**Comment by jhovgaard** [comment] 2017-03-23 21:47
@bnewman200 @metathias Can one of you send me a savegame with the money gone?

**Comment by jhovgaard** [comment] 2017-03-24 11:52
Had to play until Tier 5 to experience the same thing :D

Was caused by enabling benefits. Fixed now.

**Closed by jhovgaard** 2017-03-24 11:52 UTC
Labels: p:normal, t:bug
