### ISSUE TITLE
12.3: Tennisplate overlaps the glasswall - see picture

### ISSUE THREAD

**Issue by BadHarry00** [hovgaardgames/startupcompany#515] opened 2017-08-13 17:22 UTC
![2017-08-13 19_20_29-startup company beta 12 3](https://user-images.githubusercontent.com/30983485/29251817-92ca006e-805c-11e7-91c2-17793490eeee.png)

**Comment by johannwagner** [comment] 2017-08-13 22:03
Duplicate of #325

**Closed by johannwagner** 2017-08-13 22:03 UTC
