### ISSUE TITLE
Game not saved progress

### ISSUE THREAD

**Issue by sunnyphp** [hovgaardgames/startupcompany#483] opened 2017-08-12 12:36 UTC
Yesterday I played for a while. Exit from game correctly on Tier 9. Today, in the morning I signed up for the mod "real brands" from "cliff122", launched the game and it turned out that the progress was saved only to Tier 8.

Save game:
[sg_3ee4e214-6.zip](https://github.com/hovgaardgames/startupcompany/files/1219757/sg_3ee4e214-6.zip)

**Comment by bartusek27** [comment] 2017-08-12 19:43
Hi sunnyphp,

first off, thank you so much for your report!

Just got a question, did you launched game in the morning before installing the mod or not? So we can be sure if it was caused by mod or game itself.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by sunnyphp** [comment] 2017-08-12 20:35
No, I did not run the game before I installed the mod.

**Comment by bartusek27** [comment] 2017-08-12 20:46
Hi again,

so we can't be sure if game just didn't saved your progress, or it is a problem with a mod.
We are confident about some mods that are causing this too.

Because we don't have any more information, I need to close this issue.

Again, thanks for reporting and have fun!
Take care,
bartusek27

**Closed** 2017-08-12 20:47 UTC
Labels: s:discussion, t:bug
