### ISSUE TITLE
Object Glitching

### ISSUE THREAD

**Issue by NFHQ** [hovgaardgames/startupcompany#254] opened 2017-03-03 21:35 UTC
Ive been playing a few hours now and noticed that when i move between the floors a few of the walls (that i placed) become of centred and go to either of the back or front far corners of the square they are placed in however as soon as i move the object it becomes centred again

**Comment by InDieTasten** [comment] 2017-03-03 22:55
Duplicate of #195

**Closed by InDieTasten** 2017-03-03 22:55 UTC
