### ISSUE TITLE
Manager cant see who he/she is managing?

### ISSUE THREAD

**Issue by SirFinrod** [hovgaardgames/startupcompany#196] opened 2017-01-19 13:08 UTC
I had my manager manage one of my lead devs and then i detacthed the lead dev from his desk and put a designer instead. Then i wanted my manager to manage her. When i clicked to my manager she does not show my lead dev because he is not assigned to any desk i guess so i had to detach my designer from desk and attach lead dev back then click to my manager and unassign him then go again detach lead dev from desk and attach the designer then go to manager and assign my designer. I think even tho he is not attached to a desk we should be able to see the assigned workers. You can see in the screenshot down below my manager got 5/5 but i can only see 4 workers assigned. I believe this should be a bug. If its not i suggest this feature should be added.

I had more then one idle lead devs so i searched it first then unassigned him at that was a pain in the ass

I guess we can just use a override command like always show us who is assigned to this manager 

![startupcompany_2017-01-19_15-58-16](https://cloud.githubusercontent.com/assets/25222894/22107877/6a8b9c4a-de61-11e6-9f50-48828554ab74.png)

## Also if your move your employees to the second floor you get this 
![startupcompany_2017-01-19_18-56-31](https://cloud.githubusercontent.com/assets/25222894/22113978/0d788b2c-de79-11e6-8d16-0d8680389fe3.png)

## And also if you fire someone when your manager is assigned to him this happens : 
https://youtu.be/VE1kgYao72A

**Comment by InDieTasten** [comment] 2017-01-19 15:00
Duplicate of #192. I will keep both open, because this post has better description, but was added later

**Comment by InDieTasten** [comment] 2017-01-19 16:39
Description was edited to add two more cases, that are not covered by original issue.

**Comment by jhovgaard** [comment] 2017-01-19 22:12
Fixed.

**Closed by jhovgaard** 2017-01-19 22:12 UTC
Labels: s:duplicate
