### ISSUE TITLE
Endless loading loop

### ISSUE THREAD

**Issue by Largon84** [hovgaardgames/startupcompany#339] opened 2017-04-22 23:12 UTC
If i want to load my old save game, the game dont start!

**Comment by MrBidule** [comment] 2017-04-22 23:21
Check here:

https://github.com/hovgaardgames/startupcompany/issues/338

**Comment by jhovgaard** [comment] 2017-04-23 12:07
Duplicate of #338. Now Fixed :-)

**Closed by jhovgaard** 2017-04-23 12:07 UTC
