### ISSUE TITLE
Header and new messages blending together under inbox.

### ISSUE THREAD

**Issue by ReneDyhr** [hovgaardgames/startupcompany#193] opened 2017-01-19 10:00 UTC
![screen shot 2017-01-19 at 10 58 43 am](https://cloud.githubusercontent.com/assets/4406210/22102050/493165e6-de36-11e6-8ccb-2b369f980f6d.png)

**Comment by jhovgaard** [comment] 2017-01-19 11:48
My mistake. Duplicate of https://github.com/hovgaardgames/startupcompany/issues/166

**Closed by jhovgaard** 2017-01-19 11:48 UTC
