### ISSUE TITLE
Beta 9.7: Impossible module at level

### ISSUE THREAD

**Issue by Swinkid** [hovgaardgames/startupcompany#279] opened 2017-03-25 21:16 UTC
Just started a new game, got a contract to produce two graphics modules. Have not unlocked designer guy at this time.

![huuuh](https://cloud.githubusercontent.com/assets/6237394/24326166/25f18dfc-11a0-11e7-8928-2d7152ab31aa.png)

**Comment by InDieTasten** [comment] 2017-03-26 03:49
Possible duplicate of #260 ?

**Closed** 2017-03-26 03:51 UTC
Labels: s:duplicate
