### ISSUE TITLE
Beta 9.4: First contract received included unfulfill-able Component.

### ISSUE THREAD

**Issue by metathias** [hovgaardgames/startupcompany#260] opened 2017-03-22 01:37 UTC
Upon receiving first contract. Received request to produce compound module incapable of being fulfilled at this stage in the game. Thus requiring the player to cancel the contract.

This might be a bug, Or a feature. The player is told the necessary components to fulfill the contract, But once presented the contract has to choose to accept, or deny the contract without the capability to actually see what modules are necessary to fulfill that contract, And whether or not they have the means to do so.

**Comment by bnewman200** [comment] 2017-03-22 05:24
I received the same during T3. The contract required a compound module from the Lead Developer from T4.

**Comment by jhovgaard** [comment] 2017-03-23 15:21
Fixed. Contract generator did not know about lead dev not available until Tier 3.

@bnewman200 Modules are now only limited to Employee Level (Beginner, Intermediate and Expert) so that is actually by design :-)

**Comment by InDieTasten** [comment] 2017-03-26 03:52
Reopened, since it is occurring in beta 9.7 again.

**Comment by jhovgaard** [comment] 2017-04-01 09:43
I think @InDieTasten experienced this coming from a Designer component before designer was unlocked. This has been fixed now.

**Closed by jhovgaard** 2017-04-01 09:43 UTC
Labels: p:normal, s:approved, t:bug
