### ISSUE TITLE
Beta 12.1: Infinite percent marketshare for only product of type

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#414] opened 2017-07-20 14:55 UTC
When you have a product which is the only one of it's type, it's market share is shown as "∞%" instead of "100%" which would be more logical.
![infinite_percent_marketshare_1](https://user-images.githubusercontent.com/4162261/28423716-22c10338-6d6c-11e7-8e5d-3f1f93db88f6.png)

**Comment by jhovgaard** [comment] 2017-07-27 15:05
This was caused by missing competitors for shopping platform. Fixed now.

**Closed by jhovgaard** 2017-07-27 15:05 UTC
