### ISSUE TITLE
Furniture are overlapping

### ISSUE THREAD

**Issue by MarcoBoekholt** [hovgaardgames/startupcompany#408] opened 2017-07-17 20:48 UTC
The left chair of the **Large Meeting Table** is overlapping with the **Glass Wall**
![d5fa9c040bbfbcb496c4635e37764303](https://user-images.githubusercontent.com/1371927/28289189-0062c3d4-6b42-11e7-82aa-1f1dc8b8ff4e.jpg)

**Comment by Cliff122** [comment] 2017-07-19 23:11
Duplicate of #325?

**Comment by MarcoBoekholt** [comment] 2017-07-19 23:22
Well almost the same except its a other furniture

**Comment by jhovgaard** [comment] 2017-07-20 09:42
Updated #325 to include all items. Closing this. Thanks for reporting!

**Closed by jhovgaard** 2017-07-20 09:42 UTC
