### ISSUE TITLE
Sales Executives don't automatically get Auto Repeat when attaching a manager.

### ISSUE THREAD

**Issue by LapinoLapidus** [hovgaardgames/startupcompany#185] opened 2017-01-18 17:56 UTC
Basically, when I attach a Manager to a Sales Executive, their "Auto Repeat" button doesn't turn on automatically, however, other "roles" like Developer & Graphic Designers do get "Auto Repeat".

This is quite annoying because with all the other people, it gets put on "Auto Repeat".

**Comment by BrutalCSkakan** [comment] 2017-01-18 17:57
Developers doesn't always get Auto Repeat automatically. Probably something wrong

**Comment by InDieTasten** [comment] 2017-01-19 14:50
Duplicate of #184

**Closed by InDieTasten** 2017-01-19 14:50 UTC
Labels: s:duplicate
